-- MySQL Script generated by MySQL Workbench
-- Thu Mar 12 14:23:27 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema marsai
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema marsai
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `marsai` DEFAULT CHARACTER SET utf8mb4 ;
USE `marsai` ;

-- -----------------------------------------------------
-- Table `marsai`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marsai`.`status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marsai`.`movies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marsai`.`movies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title_original` VARCHAR(255) NOT NULL,
  `subtitles` LONGTEXT NOT NULL,
  `videofile` VARCHAR(255) NOT NULL,
  `language` VARCHAR(100) NOT NULL,
  `description` LONGTEXT NOT NULL,
  `prompt` LONGTEXT NOT NULL,
  `status` INT NOT NULL DEFAULT 1,
  `synopsis_original` LONGTEXT NOT NULL,
  `classification` VARCHAR(255) NOT NULL,
  `thumbnail` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  `title_english` VARCHAR(255) NOT NULL,
  `synospsis_english` LONGTEXT NOT NULL,
  `youtube_url` VARCHAR(255) NOT NULL,
  `movie_duration` TIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_moviestatus_idx` (`status` ASC) VISIBLE,
  CONSTRAINT `fk_movies_status`
    FOREIGN KEY (`status`)
    REFERENCES `marsai`.`status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marsai`.`ai_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marsai`.`ai_list` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ai_name` VARCHAR(100) NOT NULL,
  `included` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marsai`.`used_ai`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marsai`.`used_ai` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `movie_id` INT NOT NULL,
  `ai_name` INT NOT NULL,
  `category` ENUM("script", "movie", "postprod") NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usedai_movies_idx` (`movie_id` ASC) VISIBLE,
  INDEX `fk_usedai_ai_list_idx` (`ai_name` ASC) VISIBLE,
  CONSTRAINT `fk_usedai_movies`
    FOREIGN KEY (`movie_id`)
    REFERENCES `marsai`.`movies` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_usedai_ai_list`
    FOREIGN KEY (`ai_name`)
    REFERENCES `marsai`.`ai_list` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marsai`.`socials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marsai`.`socials` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `movie_id` INT NOT NULL,
  `social_name` VARCHAR(100) NOT NULL,
  `social_link` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_socials_idx` (`movie_id` ASC) VISIBLE,
  CONSTRAINT `fk_socials_movies`
    FOREIGN KEY (`movie_id`)
    REFERENCES `marsai`.`movies` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marsai`.`screenshots`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marsai`.`screenshots` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `movie_id` INT NOT NULL,
  `link` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_screenshots_movies_idx` (`movie_id` ASC) VISIBLE,
  CONSTRAINT `fk_screenshots_movies`
    FOREIGN KEY (`movie_id`)
    REFERENCES `marsai`.`movies` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marsai`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marsai`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `status` ENUM("admin", "jury") NOT NULL,
  `token_access` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marsai`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marsai`.`comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `movie_id` INT NOT NULL,
  `comment` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_teamid_team_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_movieid_movies_idx` (`movie_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_comments_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `marsai`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_movies_users_comments`
    FOREIGN KEY (`movie_id`)
    REFERENCES `marsai`.`movies` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marsai`.`users_movies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marsai`.`users_movies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `movie_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_movieid_movies_idx` (`movie_id` ASC) VISIBLE,
  INDEX `fk_teamid_team_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_movies_users_movies`
    FOREIGN KEY (`movie_id`)
    REFERENCES `marsai`.`movies` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_users_movies_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `marsai`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marsai`.`autoemail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marsai`.`auto_email` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `category` ENUM("validation", "redo", "refuse") NOT NULL,
  `message` VARCHAR(45) NOT NULL,
  `isactive` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_teamid_team_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_auto_email_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `marsai`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marsai`.`newsletter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marsai`.`newsletter` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marsai`.`director_profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marsai`.`director_profile` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `movie_id` INT NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `firstname` VARCHAR(100) NOT NULL,
  `lastname` VARCHAR(100) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `address2` VARCHAR(255) NOT NULL,
  `postal_code` VARCHAR(5) NOT NULL,
  `city` VARCHAR(100) NOT NULL,
  `country` VARCHAR(100) NOT NULL,
  `marketting` VARCHAR(255) NOT NULL,
  `date_of_birth` TIMESTAMP NOT NULL,
  `gender` ENUM("mr", "mme", "iel") NOT NULL,
  `fix_phone` VARCHAR(45) NULL,
  `mobile_phone` VARCHAR(45) NOT NULL,
  `school` VARCHAR(255) NOT NULL,
  `current_job` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_movieid_movies_idx` (`movie_id` ASC) VISIBLE,
  CONSTRAINT `fk_movies_director`
    FOREIGN KEY (`movie_id`)
    REFERENCES `marsai`.`movies` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marsai`.`sound_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marsai`.`sound_data` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sound` VARCHAR(255) NOT NULL,
  `type` VARCHAR(100) NOT NULL,
  `movie_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sound_data_movies_idx` (`movie_id` ASC) VISIBLE,
  CONSTRAINT `fk_sound_data_movies`
    FOREIGN KEY (`movie_id`)
    REFERENCES `marsai`.`movies` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
